### PR TITLE
1/5th'ed your image size

### PR DESCRIPTION
**Pull request by kerta1n**
Switched the base to slim but kept recommends, noticed quite a difference in pull time. Also bumped to Node 21.

### CODE REVIEW

**Comment by kerta1n** [comment]
`kertain/plexamp-docker                  4.10.1            252d881cd040   15 minutes ago   294MB
ghcr.io/anatosun/plexamp                amd64-4.10.1      1c32d5862da5   8 hours ago      1.08GB`

**Comment by kerta1n** [comment]
Found a dependency error, do not approve PR just yet, fixing in 12h

**Comment by anatosun** [comment]
Why the bump to node 21? Plexamp [uses node 20](https://www.plex.tv/media-server-downloads/?cat=headless&plat=raspberry-pi#plex-plexamp). I fear that if we use node 21 we might run into issues.

**Comment by anatosun** [comment]
Tested locally, everything seems fine. Thanks for the contribution!

**Pull request merged**
